# NumPy

## Table on Contents

* [What is an array?](#wiaa)
* [Why use NumPy?](#wun)
* [Let's get started](#lgs)
* Basics
    * [Indexing and slicing](#ias)
    * [Basic array operations](#bao)
    * [Adding, removing, and sorting elements](#arse)
    * [How do you know the shape and size of an array?](#shsiz)
    * [Can you reshape an array?](#resha)


* Array Operations and rules
    * [Broadcasting](#broad)
    * [Creating matrices](#cm)
    * [Aggregation](#aggre)


* Random
    * [Generating random numbers](#grm)


* Array Wrangling
    * [Transposing and reshaping a matrix](#trm)
    * [How to reverse an array](#revers)
    * [Reshaping and flattening multidimensional arrays](#reshflat)

<h2><p style="text-align: center;">The fundamental package for scientific computing with Python</p></h2>


<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/NumPy_logo_2020.svg/1920px-NumPy_logo_2020.svg.png" alt="Picture" width="600"/>

Nearly every scientist working in Python draws on the power of NumPy.

NumPy brings the computational power of languages like C and Fortran to Python, a language much easier to learn and use. With this power comes simplicity: a solution in NumPy is often clear and elegant.

![Numpy_scientific](images/Numpy_scientific.png)

---

NumPy's API is the starting point when libraries are written to exploit innovative hardware, create specialized array types, or add capabilities beyond what NumPy provides.

![Numpy_library_integration](images/Numpy_library_integration.png)

-----

NumPy lies at the core of a rich ecosystem of data science libraries. A typical exploratory data science workflow might look like:

![Numpy_DS](https://numpy.org/images/content_images/ds-landscape.png)

- Extract, Transform, Load: Pandas, Intake, PyJanitor
- Exploratory analysis: Jupyter, Seaborn, Matplotlib, Altair
- Model and evaluate: scikit-learn, statsmodels, PyMC3, spaCy
- Report in a dashboard: Dash, Panel, Voila

![Numpy_DS_landscape](https://numpy.org/images/content_images/data-science.png)


For high data volumes, Dask and Ray are designed to scale. Stable deployments rely on data versioning (DVC), experiment tracking (MLFlow), and workflow automation (Airflow and Prefect).


### What is an array?<a class="anchor" id="wiaa"></a>
An array is a central data structure of the NumPy library. An array is a grid of values and it contains information about the raw data, how to locate an element, and how to interpret an element. It has a grid of elements that can be indexed in various ways. The elements are all of the same type, referred to as the array dtype.

- An array can be indexed by a tuple of nonnegative integers, by booleans, by another array, or by integers. 
- The rank of the array is the number of dimensions. 
- The shape of the array is a tuple of integers giving the size of the array along each dimension.

One way we can initialize NumPy arrays is from Python lists, using nested lists for two- or higher-dimensional data.

----

### Why use NumPy?<a class="anchor" id="wun"></a>
NumPy arrays are faster and more compact than Python lists. An array consumes less memory and is convenient to use. NumPy uses much less memory to store data and it provides a mechanism of specifying the data types. This allows the code to be optimized even further.

----

### What’s the difference between a Python list and a NumPy array?
NumPy gives you an enormous range of fast and efficient ways of creating arrays and manipulating numerical data inside them. While a Python list can contain different data types within a single list, all of the elements in a NumPy array should be homogeneous. The mathematical operations that are meant to be performed on arrays would be extremely inefficient if the arrays weren’t homogeneous.

----

### Let's get started<a class="anchor" id="lgs"></a>

The NumPy library contains multidimensional array and matrix data structures. It provides ndarray, a homogeneous n-dimensional array object, with methods to efficiently operate on it. 

NumPy can be used to perform a wide variety of mathematical operations on arrays. 

It adds powerful data structures to Python that guarantee efficient calculations with arrays and matrices and it supplies an enormous library of high-level mathematical functions that operate on these arrays and matrices.

In [18]:
import numpy as np

In [19]:
a = np.array([1,2,3])

In [20]:
a

array([1, 2, 3])

In [23]:
type(a)

numpy.ndarray

In [21]:
b = [1,2,3]

In [22]:
b

[1, 2, 3]

In [24]:
type(b)

list

To create a NumPy array, you can use the function ```np.array()```.

All you need to do to create a simple array is pass a list to it. If you choose to, you can also specify the type of data in your list.

You can visualize your array this way:
![np_array](https://numpy.org/doc/stable/_images/np_array.png)

Besides creating an array from a sequence of elements, you can easily create an array filled with 0’s:

In [25]:
np.array([1,2,3,4,5,6,7,8,9])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [27]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [28]:
np.ones(20)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [30]:
# Let's say you want an array from 1 10

In [31]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

And even an array that contains a range of evenly spaced intervals. To do this, you will specify the first number, last number, and the step size.

In [33]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [34]:
np.arange(1,100,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

You can also use ```np.linspace()``` to create an array with values that are spaced linearly in a specified interval:

In [37]:
np.linspace(0,50,10)

array([ 0.        ,  5.55555556, 11.11111111, 16.66666667, 22.22222222,
       27.77777778, 33.33333333, 38.88888889, 44.44444444, 50.        ])

### Indexing and slicing<a class="anchor" id="ias"></a>
You can index and slice NumPy arrays in the same ways you can slice Python lists.

In [42]:
a = [1,2,3]

In [43]:
a[0]

1

In [44]:
data = np.array([1, 2, 3])

In [45]:
data

array([1, 2, 3])

In [41]:
data[0]

np.int64(1)

In [46]:
data[1]

np.int64(2)

In [47]:
data[2]

np.int64(3)

In [48]:
data[-1]

np.int64(3)

In [49]:
data[0:2]

array([1, 2])

### Whatever you used in list, we can use the same in a numpy array

In [53]:
data = np.array([0,1,2,3,4,5,6,7,8,9,10])

In [54]:
data[0:5]

array([0, 1, 2, 3, 4])

In [55]:
data[-10:-8]

array([1, 2])

In [56]:
data[:5]

array([0, 1, 2, 3, 4])

In [57]:
data[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
data[::2]

array([ 0,  2,  4,  6,  8, 10])

In [59]:
data[::-2]

array([10,  8,  6,  4,  2,  0])

### Let's visualise it 

In [60]:
data = np.array([1, 2, 3])

You can visualize it this way:

![np_array_index](https://numpy.org/doc/stable/_images/np_indexing.png)

You may want to take a section of your array or specific array elements to use in further analysis or additional operations. To do that, you’ll need to subset, slice, and/or index your arrays.

If you want to select values from your array that fulfill certain conditions, it’s straightforward with NumPy.

In [61]:
a = [1,2,3,[4,5,6]]

In [62]:
# For example, if you start with this array:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [63]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [64]:
a < 5

array([[ True,  True,  True,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [65]:
a > 3

array([[False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

### I can use these true/false arrays to filter my data 

In [66]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [67]:
a < 5

array([[ True,  True,  True,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [68]:
b = a < 5

In [71]:
b 

array([[ True,  True,  True,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [72]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [76]:
a[a < 7]

array([1, 2, 3, 4, 5, 6])

In [75]:
a < 7

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False]])

### IF you want, you can come up with more conditions

In [77]:
a < 2

array([[ True, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [78]:
a > 2

array([[False, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [79]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [83]:
a % 2 == 0 

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [82]:
10 % 4

2

In [86]:
# We are using the true/false array given by a % 2 == 0 to filter my numpy array a
a[a % 2 == 0]

array([ 2,  4,  6,  8, 10, 12])

In [85]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### You can filter more if you want 

In [87]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [88]:
a > 5

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [89]:
a > 7

array([[False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True]])

In [92]:
# The and operator
(a > 5) & (a > 7)

array([[False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True]])

In [93]:
# The or operator 
(a > 5) | (a > 7)

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

& <- this is the and operator 
| <- this is the or operator

### How is this useful

In [94]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [95]:
a[(a > 5) & (a < 10)]

array([6, 7, 8, 9])

In [96]:
a[(a > 5) | (a < 10)]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [97]:
(a > 5)

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [98]:
(a < 10)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True, False, False, False]])

In [99]:
(a > 5) | (a < 10)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

### Basic array operations<a class="anchor" id="bao"></a>
Once you’ve created your arrays, you can start to work with them. Let’s say, for example, that you’ve created two arrays, one called “data” and one called “ones”

![numpy_maths](https://numpy.org/doc/stable/_images/np_array_dataones.png)

You can add the arrays together with the plus sign.

In [100]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)

In [101]:
data

array([1, 2])

In [102]:
ones

array([1, 1])

In [103]:
data + ones

array([2, 3])

In [104]:
# You can, of course, do more than just addition!
print(data - ones)
print(data * data)
print(data / data)

[0 1]
[1 4]
[1. 1.]


![numpy_base_maths](https://numpy.org/doc/stable/_images/np_sub_mult_divide.png)

Basic operations are simple with NumPy. If you want to find the sum of the elements in an array, you’d use ```sum()```. This works for 1D arrays, 2D arrays, and arrays in higher dimensions.

In [105]:
a = np.array([1, 2, 3, 4])

In [106]:
a.sum()

np.int64(10)

To add the rows or the columns in a 2D array, you would specify the axis.

If you start with this array:

In [107]:
b = np.array([[1, 1], [2, 2]])

In [108]:
b

array([[1, 1],
       [2, 2]])

In [109]:
# By default it sums everything
b.sum()

np.int64(6)

In [111]:
# You can sum over the axis of rows with: row wise
b.sum(axis=1)

array([2, 4])

In [114]:
# You can sum over the axis of rows with: column wise
b.sum(axis=0)

array([3, 3])

### Adding, removing, and sorting elements<a class="anchor" id="arse"></a>
Sorting an element is simple with np.sort(). You can specify the axis, kind, and order when you call the function.

In [115]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [116]:
arr

array([2, 1, 5, 3, 7, 4, 6, 8])

In [117]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

You can concatenate them with ```np.concatenate()```.

In [118]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [119]:
a

array([1, 2, 3, 4])

In [120]:
b

array([5, 6, 7, 8])

In [121]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

### What if we have multi-dimensional data

In [122]:
mul_b = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [123]:
mul_b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [126]:
c = np.array([[10,10,10,10]])

In [128]:
c

array([[10, 10, 10, 10]])

In [129]:
mul_b * c

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120]])

In [131]:
### Look closely for the shape of the arrays 

In [133]:
mul_b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [134]:
mul_b.shape

(3, 4)

In [135]:
a = np.array([1,2,3])

In [136]:
a.shape

(3,)

In [137]:
b = np.array([[1,2,3],[4,5,6]])

In [138]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [139]:
b.shape

(2, 3)

### If you use a single list as an input you'll get 1D array, if you use a list of list as an input, you'll get 2D array

In [140]:
a = np.array([[1,2,3]])

In [141]:
a

array([[1, 2, 3]])

In [142]:
a.shape

(1, 3)

### How do you know the shape and size of an array?<a class="anchor" id="shsiz"></a>

```ndarray.ndim``` will tell you the number of axes, or dimensions, of the array.

```ndarray.size``` will tell you the total number of elements of the array. This is the product of the elements of the array’s shape.

```ndarray.shape``` will display a tuple of integers that indicate the number of elements stored along each dimension of the array. If, for example, you have a 2-D array with 2 rows and 3 columns, the shape of your array is (2, 3).

In [143]:
a.shape

(1, 3)

In [144]:
a.size

3

In [146]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [147]:
array_example

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [148]:
array_example.ndim

3

In [149]:
array_example.size

24

In [150]:
array_example.shape

(3, 2, 4)

### Broadcasting<a class="anchor" id="broad"></a>
There are times when you might want to carry out an operation between an array and a single number or between arrays of two different sizes. For example, your array (we’ll call it “data”) might contain information about distance in miles but you want to convert the information to kilometers.

In [151]:
# You can perform this operation with:
data = np.array([1.0, 2.0])

In [152]:
data

array([1., 2.])

In [153]:
data * 1.6

array([1.6, 3.2])

![numpy_broadcast](https://numpy.org/doc/stable/_images/np_multiply_broadcasting.png)

NumPy understands that the multiplication should happen with each cell. That concept is called broadcasting. Broadcasting is a mechanism that allows NumPy to perform operations on arrays of different shapes. The dimensions of your array must be compatible, for example, when the dimensions of both arrays are equal or when one of them is 1. If the dimensions are not compatible, you will get a ```ValueError```.

### More useful array operations
NumPy also performs aggregation functions. In addition to ```min```, ```max```, and ```sum```, you can easily run mean to get the average, prod to get the result of multiplying the elements together, std to get the standard deviation, and more.

In [154]:
data.min()

np.float64(1.0)

In [155]:
data.max()

np.float64(2.0)

In [156]:
data.sum()

np.float64(3.0)

![numpy_agg](https://numpy.org/doc/stable/_images/np_aggregation.png)

In [157]:
b = np.array([[1,2,3],[4,5,6]])

In [158]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [162]:
b * np.array([1,2,3])

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [163]:
b.shape

(2, 3)

In [164]:
np.array([1,2]).shape

(2,)

In [161]:
b * np.array([1,2])

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

### What is wrong with numpy that we have to use pandas 

In [166]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [167]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [168]:
c = np.array([[1,2,3],[4,5,6],[7,8,'Siddharth']])

In [169]:
c

array([['1', '2', '3'],
       ['4', '5', '6'],
       ['7', '8', 'Siddharth']], dtype='<U21')

In [170]:
c = np.array([[1,2,'CR7'],[4,5,'Messi'],[7,8,'Siddharth']])

In [171]:
c

array([['1', '2', 'CR7'],
       ['4', '5', 'Messi'],
       ['7', '8', 'Siddharth']], dtype='<U21')

### Numpy array will force the same data type

In [172]:
a = np.array([1,2,3,4,5,6])

In [173]:
a

array([1, 2, 3, 4, 5, 6])

In [174]:
a = np.array([1,2,3,4,5,6.5])

In [175]:
a

array([1. , 2. , 3. , 4. , 5. , 6.5])

In [176]:
a = np.array([1,2,3,4,5,6, 'sid'])

In [177]:
a

array(['1', '2', '3', '4', '5', '6', 'sid'], dtype='<U21')

In [178]:
a = np.array([1,2,3,4,5,6])

In [179]:
a.sum()

np.int64(21)