In [24]:
import numpy as np
import matplotlib.pyplot as plt
from utils import plot_lines

In [25]:
A = np.array([
        [-1, 3],
        [3, 2]
    ], dtype=np.dtype(float))

b = np.array([7, 1], dtype=np.dtype(float))

print("Matrix A:")
print(A)
print("\nArray b:")
print(b)

Matrix A:
[[-1.  3.]
 [ 3.  2.]]

Array b:
[7. 1.]


In [26]:
print(f"Shape of A: {A.shape}")
print(f"Shape of b: {b.shape}")

# print(f"Shape of A: {np.shape(A)}")
# print(f"Shape of A: {np.shape(b)}")

Shape of A: (2, 2)
Shape of b: (2,)


In [27]:
x = np.linalg.solve(A, b)

print(f"Solution: {x}")

Solution: [-1.  2.]


In [28]:
d = np.linalg.det(A)

print(f"Determinant of matrix A: {d:.2f}")

Determinant of matrix A: -11.00


In [29]:
A_system = np.hstack((A, b.reshape((2, 1))))

print(A_system)

[[-1.  3.  7.]
 [ 3.  2.  1.]]


In [30]:
print(A_system[1])

[3. 2. 1.]


In [31]:
plot_lines(A_system)

NameError: name 'np' is not defined

In [ ]:
A_2 = np.array([
        [-1, 3],
        [3, -9]
    ], dtype=np.dtype(float))

b_2 = np.array([7, 1], dtype=np.dtype(float))

d_2 = np.linalg.det(A_2)

print(f"Determinant of matrix A_2: {d_2:.2f}")

Determinant of matrix A_2: 0.00


In [ ]:
A_2_system = np.hstack((A_2, b_2.reshape((2, 1))))
print(A_2_system)   

[[-1.  3.  7.]
 [ 3. -9.  1.]]


In [ ]:
plot_lines(A_2_system)

NameError: name 'np' is not defined

In [ ]:
b_3 = np.array([7, -21], dtype=np.dtype(float))

In [ ]:
A_3_system = np.hstack((A_2, b_3.reshape((2, 1))))
print(A_3_system)

[[ -1.   3.   7.]
 [  3.  -9. -21.]]


In [ ]:
plot_lines(A_3_system)

NameError: name 'np' is not defined